version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      - docker run -v ./test.js:/test.js -i loadimpact/k6 run /test.js
  post_build:
    commands:
      - echo Performance test complete
